services:
  flower_db:
    image: mysql:8.0
    container_name: flower_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flower_shop_db
    ports:
      - "3306:3306"

  flower_app:
    build: .
    depends_on:
      - flower_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://flower_db:3306/flower_shop_db