spring.application.name=flower_shop

spring.datasource.url=jdbc:mysql://localhost:3306/flower_shop_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true